name: Tests
on:
  push:
  pull_request:

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python:
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - run: python -m pip install -U pip
      - run: python -m pip install setuptools wheel flake8 twine pytest

      - run: python setup.py sdist bdist_wheel
      - run: python -m pip install dist/*.whl

      - run: twine check dist/*
      - run: flake8
      - run: pytest
      - run: python -m doctest README.rst

      - name: Publish PyPI package
        if: startsWith(github.ref, 'refs/tags/v') &&
            matrix.os == 'ubuntu-latest' &&
            matrix.python == '3.8'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*.whl dist/*.tar.gz
