name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron: '12 20  *  *  1'

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python:
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - run: python -m pip install -U pip
      - run: python -m pip install setuptools wheel twine
      - run: python -m pip install flake8 pytest coverage

      - run: python setup.py sdist bdist_wheel
      - run: python -m pip install dist/*.whl

      - run: twine check dist/*
      - run: flake8
      - run: coverage run --source=funcwrap -m pytest

      - name: Publish PyPI package
        if: startsWith(github.ref, 'refs/tags/v') &&
            matrix.os == 'ubuntu-latest' &&
            matrix.python == '3.8'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*.whl dist/*.tar.gz

      - run: bash <(curl -s https://codecov.io/bash)
        if: env.CODECOV_TOKEN != ''
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
